In [0]:
import numpy as np

In [0]:
class Node():
    def __init__(self,state,parent,action,step_cost,heuristic_cost,actual_cost):
        self.state = state 
        self.parent = parent
        self.action = action
        self.step_cost = step_cost
        self.heuristic_cost = heuristic_cost
        self.actual_cost = actual_cost
        
  
        self.move_up = None 
        self.move_left = None
        self.move_down = None
        self.move_right = None
        
    def index_of_zero(self):
      for i in range(3):
        for j in range(3):
          if self.state[i,j] == 0:
            index = [i,j]
            return index
    
 
    def try_move_down(self):
        zero_index= self.index_of_zero()
        if zero_index[0] == 0:
            return False
        else:
            up_value = self.state[zero_index[0]-1,zero_index[1]]
            new_state = self.state.copy()
            new_state[zero_index[0],zero_index[1]] = up_value
            new_state[zero_index[0]-1,zero_index[1]] = 0
            return new_state,up_value
        
    def try_move_right(self):
        zero_index= self.index_of_zero()
        if zero_index[1] == 0:
            return False
        else:
            left_value = self.state[zero_index[0],zero_index[1]-1]
            new_state = self.state.copy()
            new_state[zero_index[0],zero_index[1]] = left_value
            new_state[zero_index[0],zero_index[1]-1] = 0
            return new_state,left_value
        
    def try_move_up(self):
        zero_index= self.index_of_zero()
        if zero_index[0] == 2:
            return False
        else:
            lower_value = self.state[zero_index[0]+1,zero_index[1]]
            new_state = self.state.copy()
            new_state[zero_index[0],zero_index[1]] = lower_value
            new_state[zero_index[0]+1,zero_index[1]] = 0
            return new_state,lower_value
        
    def try_move_left(self):
        zero_index= self.index_of_zero()
        if zero_index[1] == 2:
            return False
        else:
            right_value = self.state[zero_index[0],zero_index[1]+1]
            new_state = self.state.copy()
            new_state[zero_index[0],zero_index[1]] = right_value
            new_state[zero_index[0],zero_index[1]+1] = 0
            return new_state,right_value
    
    def h_manhattan_cost(self,new_state):
        current = new_state
        goal_position = {0:(0,0),1:(0,1),2:(0,2),3:(1,0),4:(1,1),5:(1,2),6:(2,0),7:(2,1),8:(2,2)} 
        sum_manhattan = 0
        for i in range(3):
            for j in range(3):
                if current[i,j] != 0:
                    x = goal_position[current[i,j]]
                    sum_manhattan = sum_manhattan + abs(i- x[0]) + abs(j-x[1])
        return sum_manhattan
        
    def print_path(self):
        state_trace = [self.state]
        action_trace = [self.action]
        step_cost_trace = [self.step_cost]
        
        while self.parent:
            self = self.parent

            state_trace.append(self.state)
            action_trace.append(self.action)
            step_cost_trace.append(self.step_cost)

        while state_trace:
            print (state_trace.pop())
            print ('action=',action_trace.pop(),'the tile ',step_cost_trace.pop(),'\n')
            
            
    def a_StarSearch(self,goal_state):
        
        queue = [(self,0)]
        visited = set([])
        step = 0
        
        while queue:
            queue = sorted(queue, key=lambda x: x[1])    
                
            current_node = queue.pop(0)[0]
            g_cost = self.actual_cost + 1
            
            visited.add(tuple(current_node.state.reshape(1,9)[0]))
            
            if np.array_equal(current_node.state,goal_state):
                current_node.print_path()
                return True
            
            else:     
                if current_node.try_move_down():
                    new_state,up_value = current_node.try_move_down()
                    
                    if tuple(new_state.reshape(1,9)[0]) not in visited:
                        h_cost = self.h_manhattan_cost(new_state)
                        total_cost = g_cost + h_cost
                        current_node.move_down = Node(state=new_state,parent=current_node,action='down',step_cost=up_value,heuristic_cost=h_cost,actual_cost=g_cost)
                        queue.append((current_node.move_down, total_cost))
                    
                if current_node.try_move_right():
                    new_state,left_value = current_node.try_move_right()
                    if tuple(new_state.reshape(1,9)[0]) not in visited:
                        h_cost = self.h_manhattan_cost(new_state)
                        total_cost = g_cost + h_cost
                        current_node.move_right = Node(state=new_state,parent=current_node,action='right',step_cost=left_value,heuristic_cost=h_cost,actual_cost=g_cost)
                        queue.append((current_node.move_right, total_cost))
                    
                if current_node.try_move_up():
                    new_state,lower_value = current_node.try_move_up()
                    if tuple(new_state.reshape(1,9)[0]) not in visited:
                        h_cost = self.h_manhattan_cost(new_state)
                        total_cost = g_cost + h_cost
                        current_node.move_up = Node(state=new_state,parent=current_node,action='up',step_cost=lower_value,heuristic_cost=h_cost,actual_cost=g_cost)
                        queue.append((current_node.move_up, total_cost))

                if current_node.try_move_left():
                    new_state,right_value = current_node.try_move_left()
                    if tuple(new_state.reshape(1,9)[0]) not in visited:
                        h_cost = self.h_manhattan_cost(new_state)
                        total_cost = g_cost + h_cost
                        current_node.move_left = Node(state=new_state,parent=current_node,action='left',step_cost=right_value,heuristic_cost=h_cost,actual_cost=g_cost)
                        queue.append((current_node.move_left, total_cost))

In [3]:

puzzle = np.array([[3,0,7],[2,8,1],[6,4,5]])

goal_state = np.array([0,1,2,3,4,5,6,7,8]).reshape(3,3)
print (puzzle,'\n')
print (goal_state)

[[3 0 7]
 [2 8 1]
 [6 4 5]] 

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
root = Node(state=puzzle,parent=None,action=None,step_cost=0,heuristic_cost=0,actual_cost=0)
root.a_StarSearch(goal_state)

[[3 0 7]
 [2 8 1]
 [6 4 5]]
action= None the tile  0 

[[3 7 0]
 [2 8 1]
 [6 4 5]]
action= left the tile  7 

[[3 7 1]
 [2 8 0]
 [6 4 5]]
action= up the tile  1 

[[3 7 1]
 [2 0 8]
 [6 4 5]]
action= right the tile  8 

[[3 7 1]
 [0 2 8]
 [6 4 5]]
action= right the tile  2 

[[0 7 1]
 [3 2 8]
 [6 4 5]]
action= down the tile  3 

[[7 0 1]
 [3 2 8]
 [6 4 5]]
action= left the tile  7 

[[7 2 1]
 [3 0 8]
 [6 4 5]]
action= up the tile  2 

[[7 2 1]
 [3 4 8]
 [6 0 5]]
action= up the tile  4 

[[7 2 1]
 [3 4 8]
 [6 5 0]]
action= left the tile  5 

[[7 2 1]
 [3 4 0]
 [6 5 8]]
action= down the tile  8 

[[7 2 0]
 [3 4 1]
 [6 5 8]]
action= down the tile  1 

[[7 0 2]
 [3 4 1]
 [6 5 8]]
action= right the tile  2 

[[0 7 2]
 [3 4 1]
 [6 5 8]]
action= right the tile  7 

[[3 7 2]
 [0 4 1]
 [6 5 8]]
action= up the tile  3 

[[3 7 2]
 [4 0 1]
 [6 5 8]]
action= left the tile  4 

[[3 0 2]
 [4 7 1]
 [6 5 8]]
action= down the tile  7 

[[3 2 0]
 [4 7 1]
 [6 5 8]]
action= left the tile  2 

[[3 2 1]
 [4 7

True